# This is a basic workflow to help you get started with Actions
name: GitHub Actions Demo
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
   # branches: [ "main" ]
  #pull_request:
   # branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains the following jobs: "Initialization & Build"
  initialization:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.DetermineNextTagVersion.outputs.new_tag }}
      current_version: ${{ steps.DetermineNextTagVersion.outputs.tag }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Determine Next Tag Version
        id: DetermineNextTagVersion
        uses: anothrNick/github-tag-action@1.39.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERBOSE: true
          DRY_RUN: true
  build:
    runs-on: ubuntu-latest
    needs: initialization
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: github
      - name: Build with Maven
        run: mvn clean package
