name: GitHub Actions Demo
on:
  #push:
   # branches: [ "main" ]
  #pull_request:
   # branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  initialization:
    runs-on: ubuntu-latest
    outputs:
      next_version: ${{ steps.DetermineNextTagVersion.outputs.new_tag }}
      current_version: ${{ steps.DetermineNextTagVersion.outputs.tag }}
    steps:
      - uses: actions/checkout@v3
      - name: Determine Next Tag Version
        id: DetermineNextTagVersion
        uses: anothrNick/github-tag-action@1.39.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERBOSE: true
          DRY_RUN: true
  build:
    runs-on: ubuntu-latest
    needs: initialization
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: github
      - name: Build with Maven
        run: mvn clean package 
      - name: Print Next Tag
        run: echo ${{needs.initialization.outputs.next_version}}
  publish:
    runs-on: ubuntu-latest 
    needs: [initialization, build]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Set Release version
        run: mvn versions:set -DnewVersion=${{needs.initialization.outputs.next_version}}
      - name: Publish to GitHub Packages Apache Maven
        run: echo 'Skipping publish stage.'
        #run: mvn --batch-mode -DuseGitHubPackages=true deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  set_Release:
    runs-on: ubuntu-latest
    needs: [initialization, build, publish]
    steps:
    - uses: actions/checkout@v3
    - name: Create a Release
      uses: elgohr/Github-Release-Action@v4
      env:
        GITHUB_TOKEN: ${{ secrets.IMK_RELEASE_TOKEN }}
      with:
        title: ${{needs.initialization.outputs.next_version}}
    - name: Determine Next Tag Version
      id: DetermineNextTagVersion
      uses: anothrNick/github-tag-action@1.39.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}